{% set name = "perplexityai" %}
{% set version = "0.29.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/perplexityai-{{ version }}.tar.gz
  sha256: 7c37a267d8e5dec1a640f201dd569edf9247a185e29465c2e3dab13108706264

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling ==1.26.3
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing_extensions >=4.10,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio

test:
  imports:
    - perplexity
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/perplexityai/perplexity-py
  summary: The official Python library for the perplexity API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Aleksei-Poliakov
