schema_version: 1

context:
  version: "0.43.5"

package:
  name: perplexityai
  version: ${{ version }}

source:
  url: https://github.com/perplexityai/perplexity-py/archive/refs/tags/v${{ version }}.tar.gz
  sha256: fa6f1a8096525a642754ce1f9123d978954e085e3fc9f80bd35e2a684a8fd58d
  # https://github.com/perplexityai/perplexity-py/pull/120
  patches:
    - license.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling ==1.26.3
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=${{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing_extensions >=4.14,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio

tests:
  - python:
      imports:
        - perplexity
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: The official Python library for the perplexity API
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/perplexityai/perplexity-py

extra:
  recipe-maintainers:
    - Aleksei-Poliakov
